### ISSUE TITLE
Error on Developer App Analytics page for Hybrid Org

### ISSUE THREAD

**Issue by varuntit101** [apigee/apigee-client-php#105]
## Description
After creating a App, On Analytics page I am seeing below error:-
"Unable to retrieve analytics data. Please try again."

On checking Drupal logs I saw below error message:-
"Apigee\Edge\Exception\ClientErrorException: INVALID_ARGUMENT: Invalid JSON payload received. Unknown name "_optimized": Cannot bind query parameter. Field 'optimized' could not be found in request message. in Apigee\Edge\HttpClient\Plugin\ResponseHandlerPlugin->decodeResponse() (line 104 of G:\Projects\apigee_kickstart\vendor\apigee\apigee-client-php\src\HttpClient\Plugin\ResponseHandlerPlugin.php)."

Refer screenshot for Apigee Debug message of Request and Response

## Version Info
2.0.5

![image](https://user-images.githubusercontent.com/9864661/91217681-817da700-e735-11ea-8b42-91b0904b956e.png)
![image](https://user-images.githubusercontent.com/9864661/91218232-5f385900-e736-11ea-886b-0c0de1b4740a.png)

**Comment by arlina-espinoza** [comment]
Should be fixed by #111 .
