### ISSUE TITLE
Notice in recent message logs if description is empty after creating app in Apigee hybrid

### ISSUE THREAD

**Issue by varuntit101** [apigee/apigee-client-php#108]
## Description
Notice in recent message logs if description is empty after creating app in Apigee hybrid

## Steps to Reproduce
Create an app with empty description

`Notice: Undefined property: stdClass::$value in Apigee\Edge\Denormalizer\AttributesPropertyDenormalizer->denormalize() (line 57 of \vendor\apigee\apigee-client-php\src\Denormalizer\AttributesPropertyDenormalizer.php)`

**Comment by mxr576** [comment]
@shishir-intelli please add test coverage to #122 if you have time, that is required to merge the fix.
