### ISSUE TITLE
DeveloperController::getDeveloperByApp() is incorrectly implemented

### ISSUE THREAD

**Issue by mxr576** [apigee/apigee-client-php#116]
## Description
[According to the official documentation](https://apidocs.apigee.com/docs/developers/1/routes/organizations/%7Borg_name%7D/developers/get) `\Apigee\Edge\Api\Management\Controller\DeveloperController::getDeveloperByApp()` is incorrectly implemented because the related API endpoint returns _an array of developer objects_ instead of one developer object.

> To get the developers associated with a specific app, specify the name of the app using the app query parameter.

## Notes
Since fixing this requires a change in the related [interface](https://github.com/apigee/apigee-client-php/blob/2.x/src/Api/Management/Controller/DeveloperControllerInterface.php#L54) we have to be careful about how we introduce this fix. Probably we should do the following:
* keep the interface unchanged
* trigger a warning in the default implementation of [DeveloperController::getDeveloperByApp()](https://github.com/apigee/apigee-client-php/blob/2.x/src/Api/Management/Controller/DeveloperController.php#L69) to let downstream devs know that the method works incorrectly, they should use the new method that we introduce in the next step.
* introduce a new `getDevelopersByAppName()` in the `DeveloperController` with a todo that this method should be added to the `DeveloperControllerInterface` in 3.0.0.
* leave a todo on `DeveloperController::getDeveloperByApp()` and `DeveloperControllerInterface::getDeveloperByApp()` to get them removed in 3.0.0.

## Version Info
2.0.6

**Comment by raakesh-blokhra** [comment]
@phdhiren can you look at this one or close if not needed any more?

**Comment by mxr576** [comment]
`sudo re-open`
