### ISSUE TITLE
Upgrade PHP version for Travis-Ci to PHP 7.3+

### ISSUE THREAD

**Issue by raakesh-blokhra** [apigee/apigee-client-php#124]
## Description
Travis-Ci is using PHP 7.1 currently which is causing the tests to fail since it not familiar with the syntax changes of higher PHP versions. 
## Steps to Reproduce
Create a new branch from fork and run Travis-Ci tests
## Actual Behavior
Tests are failing (syntax errors)

## Expected Behavior
Tests should pass since no changes have been made to the branch

## Version Info
travis-ci.com (recommended newer version of travis-ci.org)

**Comment by mxr576** [comment]
There is a related conversation in https://github.com/apigee/apigee-client-php/pull/121

Points like:

> > PHP versions we test against and support should be 7.3. and 7.4 since < 7.3 is end of life: https://www.php.net/supported-versions.php

> Well true, but you cannot be sure about who uses Zend's LTS versions, so throwing way <7.3 is not that simple.  (We have met a customer who does, so 7.1 support is still required...) Also before, if we would like to play nice, before we would throw away support of a PHP version we should announce it in time and let developers time to adapt. Check Symfony's and Drupal's philosophy about this topic. 
> https://www.zend.com/sites/zend/files/image/2020-06/image-zend-compare-php-support-zend-server.jpg

**Comment by cnovak** [comment]
> There is a related conversation in #121

See my comments in #121

**Comment by phdhiren** [comment]
PHP 7.3 travis-ci testing already in place with pull #121
