### ISSUE TITLE
Deprecation warnings when called serialized classes from the Symfony framework 4.4.x.

### ISSUE THREAD

**Issue by kruczi** [apigee/apigee-client-php#143]
## Description
During the development of PHPUnit tests, I discovered deprecation warnings caused by SDK `apigee/apigee-client-php`.

## Warnings
1) 
  1x: Passing configuration options directly to the constructor is deprecated since Symfony 4.2, use the default context instead.

- constructor with warning
  vendor/symfony/serializer/Normalizer/DateTimeNormalizer.php
  ```
  public function __construct($defaultContext = [], \DateTimeZone $timezone = null)
    {
        $this->defaultContext = [
            self::FORMAT_KEY => \DateTime::RFC3339,
            self::TIMEZONE_KEY => null,
        ];

        if (!\is_array($defaultContext)) {
            @trigger_error('Passing configuration options directly to the constructor is deprecated since Symfony 4.2, use the default context instead.', \E_USER_DEPRECATED);

            $defaultContext = [self::FORMAT_KEY => (string) $defaultContext];
            $defaultContext[self::TIMEZONE_KEY] = $timezone;
        }

        $this->defaultContext = array_merge($this->defaultContext, $defaultContext);
    }
  ```

- cause
  vendor/apigee/apigee-client-php/src/Api/Monetization/Serializer/EntitySerializer.php
  ```
  new DateTimeNormalizer(EntityInterface::DATE_FORMAT, new \DateTimeZone('UTC')),
  ```

2)
  1x: Using constructor parameters that are not a default context is deprecated since Symfony 4.2, use the "json_decode_associative" and "json_decode_recursion_depth" keys of the context instead.

- constructor with warning
  vendor/symfony/serializer/Encoder/JsonDecode.php
  ```
  public function __construct($defaultContext = [], int $depth = 512)
    {
        if (!\is_array($defaultContext)) {
            @trigger_error(sprintf('Using constructor parameters that are not a default context is deprecated since Symfony 4.2, use the "%s" and "%s" keys of the context instead.', self::ASSOCIATIVE, self::RECURSION_DEPTH), \E_USER_DEPRECATED);

            $defaultContext = [
                self::ASSOCIATIVE => (bool) $defaultContext,
                self::RECURSION_DEPTH => $depth,
            ];
        }

        $this->defaultContext = array_merge($this->defaultContext, $defaultContext);
    }
  ```

- cause
  vendor/apigee/apigee-client-php/src/Serializer/JsonDecode.php
  ```
  parent::__construct($associative, $depth);
  ```

3)
  1x: Passing an integer as first parameter of the "Symfony\Component\Serializer\Encoder\JsonEncode::__construct()" method is deprecated since Symfony 4.2, use the "json_encode_options" key of the context instead.

- constructor with warning
  vendor/symfony/serializer/Encoder/JsonEncode.php

```
public function __construct($defaultContext = [])
    {
        if (!\is_array($defaultContext)) {
            @trigger_error(sprintf('Passing an integer as first parameter of the "%s()" method is deprecated since Symfony 4.2, use the "json_encode_options" key of the context instead.', __METHOD__), \E_USER_DEPRECATED);

            $this->defaultContext[self::OPTIONS] = (int) $defaultContext;
        } else {
            $this->defaultContext = array_merge($this->defaultContext, $defaultContext);
        }
    }
```

- cause
vendor/apigee/apigee-client-php/src/Serializer/JsonEncoder.php
    ```
     parent::__construct(new JsonEncode(JSON_PRESERVE_ZERO_FRACTION), $decodingImpl);
    ```

## Version Info
Symfony: 4.4.x
Drupal core: 9.1.7
apigee/apigee-client-php: 2.0.7

**Comment by mxr576** [comment]
Probably related to #110, we should make sure we do not use deprecated APIs of our dependencies and check compatibility for every supported version in the range. This is what the highest-lowest testing is for.
