### ISSUE TITLE
Migrate from travis-ci.org to travis-ci.com

### ISSUE THREAD

**Issue by phdhiren** [apigee/apigee-client-php#155]
## Description
https://travis-ci.org/ is no longer supporting testing, they have asked to migrate to https://travis-ci.com

We need to move over our Apigee Repos to https://travis-ci.com/account/migrate

## Actual Behavior
Currently all test are running as it goes to travis-ci.org

## Expected Behavior
Tests should run on raising PR

**Comment by mxr576** [comment]
Have you also considered Github Actions which is free for FOSS projects like this?

**Comment by mxr576** [comment]
Some works has been already made here: https://github.com/apigee/apigee-client-php/pull/127

**Comment by phdhiren** [comment]
travis-ci.com is in action for any new PR / build.
