### ISSUE TITLE
{@inheritdoc} instead of `@inheritdoc` to avoid phpdoc_tag_type error

### ISSUE THREAD

**Issue by shishir-intelli** [apigee/apigee-client-php#157]
IIRC it was intentionally `@inheritdoc` instead of the inlined version of it. Besides, it is an unrelated change, so I would propose changing this in a separate CR.

_Originally posted by @mxr576 in https://github.com/apigee/apigee-client-php/pull/154#discussion_r659284343_

**Comment by mxr576** [comment]
phpdoc_tag_type? In where? Maybe the problem is that it is `@inheritdoc` instead of `@inheritDoc`?

**Comment by shishir-intelli** [comment]
![image](https://user-images.githubusercontent.com/75600200/123755433-840ed700-d8d9-11eb-9d41-9184a76968ee.png)
If it is `@inheritdoc` or `@inheritDoc` the php-cs-fixer throws the above error.

Is we change it to inline `{@inheritdoc}` it works
![image](https://user-images.githubusercontent.com/75600200/123755350-6d688000-d8d9-11eb-9c01-9c38143a445f.png)
