### ISSUE TITLE
The library is not compatibale with latest Drupal (9.2) and Apigee Edge module (1.23)

### ISSUE THREAD

**Issue by VladimirAus** [apigee/apigee-client-php#161]
## Problem

* Install Drupal (9.2) and Apigee Edge module (1.23)
* The latest version `2.0.8` is not compatible with the above setup.  Only version `2.0.6` is compatible.

## Proposed solution 

* Remove conflict for `"symfony/polyfill-mbstring": ">1.20.0"`
* Remove support for PHP 7.1 and 7.2 in tests as versions are not longer supported https://www.php.net/supported-versions.php
* Add support for PHP 7.4 

## Related issues

* https://github.com/apigee/apigee-edge-drupal/issues/600
* https://github.com/apigee/apigee-client-php/issues/146

**Comment by phdhiren** [comment]
This should be solved with the PR https://github.com/apigee/apigee-client-php/pull/166
