### ISSUE TITLE
https://github.com/php-http/client-common/pull/103 has been closed.

### ISSUE THREAD

**Issue by Jaesin** [apigee/apigee-client-php#21]
The `php-http/client-common` library has a new release So the patch (`https://patch-diff.githubusercontent.com/raw/php-http/client-common/pull/103.diff`) should no longer be necessary.

**Comment by mxr576** [comment]
@Jaesin Please see the related which I have created last week: https://github.com/apigee/apigee-client-php/pull/20

Unfortunately the new version from client-common introduced breaking changes. They are working on a fix for that, but if they could not fix it until Wednesday I'll create a new release and add client-common >= 1.8.0 as a conflict to our lib.

**Comment by mxr576** [comment]
Blocked php-http/client-common:1.8.0, only that version contains the mention patch so it is still required: https://github.com/php-http/client-common/commit/e35c5f3f74707760e1ced52f8533121b8072feb5
