### ISSUE TITLE
PHP version mis-match -  Packagist  vs. Github Actions 

### ISSUE THREAD

**Issue by gosunilgo** [apigee/apigee-client-php#235]
## Description

Currently, Github Actions file is building 8.1 & 8.2, whereas packagist repo allows 7.4 and 8.0.   This leads to confusion with enterprise CI lifecycle -   eg. Artifactory reverses-proxies a known source packagist. 

## Steps to Reproduce
See version on packagist - 

> https://packagist.org/packages/apigee/apigee-client-php
> requires php: ^7.4 || ^8.0

See github actions - https://github.com/apigee/apigee-client-php/blob/2.x/.github/workflows/php-test-workflow.yml#L22
>                -   php: '8.1'
>                    dependencies-preference: " "

## Actual Behavior
N/A  - Lifecycle/Release Management

## Expected Behavior
Keep github-actions & composer.json / packagist in-sync -   Example,  Looks like php 8.0 and php 8.1 is current supported version?  If so, please drop 7.4 and add 8.1

## Screenshots
https://github.com/apigee/apigee-client-php/blob/2.x/composer.json
vs. 
https://packagist.org/packages/apigee/apigee-client-php

## Notes
N/A

## Version Info
N/A

**Comment by mxr576** [comment]
Related to this, PHP 7.4 support was dropped from the Drupal connector as part of https://github.com/apigee/apigee-edge-drupal/issues/767, most probably it is time to drop it from this component too.

**Comment by mxr576** [comment]
FTR, ` ^8.0` means `8.0.x`, `8.1.x`, `8.2.x`..... `8.99.x`... 

Most probably it would be wiser to sail off safer oceans and start locking on PHP minor versions as they tend to introduce breaking changes every time. Composer could pick the correct version of the PHP API client more easily (not the developer would not figure out later that the installed version by Composer is actually not yet PHP 8.2 compatible...).
