### ISSUE TITLE
Update apigee-client-php to use Symfony 6.2

### ISSUE THREAD

**Issue by giteshk** [apigee/apigee-client-php#254]
Upgrade to Symfony 5.4 as an intermediate step to symfony 6 upgrade.

**Comment by mxr576** [comment]
> Update apigee-client-php to use Symfony 6.2

...to also support 6.2? So we should not leave [still-supported Symfony versions](https://symfony.com/releases) behind, right? Drupal is potentially not the only consumer of this PHP library.

**Comment by divya-intelli** [comment]
Fixed in PR #262 .
