### ISSUE TITLE
PHP Errors when upgrading to Symfony 5.4

### ISSUE THREAD

**Issue by giteshk** [apigee/apigee-client-php#257]
Below are errors reported  when upgrading Symfony components to version 5.4 :

1. Attempt to read property "developer" on array
2. TypeError: array_slice(): Argument # 2 ($offset) must be of type int, string given
3. Attempt to read property "type" on array
4. Symfony\Component\Serializer\Exception\UnexpectedValueException: Unable to denormalize because both "developerId" and "companyName" are missing from data.
5. Failed asserting that exception of type "TypeError" matches expected exception "\InvalidArgumentException". Message was: "Symfony\Component\Serializer\Encoder\JsonDecode::__construct(): Argument # 1 ($defaultContext) must be of type array, bool given, called in FileSystemResponseFactory.php on line 65"
6. Error: Cannot instantiate abstract class Apigee\Edge\Api\Monetization\Structure\Reports\Criteria\AbstractCriteria

**Comment by divya-intelli** [comment]
As per symfony's steps to upgrade , it is recommended to first upgrade to [5.4](https://symfony.com/doc/current/setup/upgrade_major.html#1-make-your-code-deprecation-free). 
The above errors are fixed in PR #262. Hence closing this issue.
