### ISSUE TITLE
BC breaks were merged to drupal10-prep branch

### ISSUE THREAD

**Issue by mxr576** [apigee/apigee-client-php#269]
## Description

Parameter types and return types were changed as part of #262, like in the [Builder class](https://github.com/apigee/apigee-client-php/commit/5e4def5771d96596ca66746757ebfb3bef23b52f#diff-0b5dacffeb3c585dbd039b01f2956229d3315173b5cba1deed0f742f764d6526).

Changing parameter types and return types on public APIs can be considered a BC break. Would be great if these changes would not land in 2.x rather in 3.x branch. That is the only way to tell Composer (the package manager) that not to update automatically to this release because it may introduce breaking changes for customization.

A similar story about return type-hints from Symfony: https://github.com/symfony/symfony/issues/43021

**Comment by mxr576** [comment]
> Changing parameter types

Needs to be double checked, but as long as all new types is **less specific** than (IOW it is a parent of) the original one, this can be fine,.

**Comment by divya-intelli** [comment]
@mxr576 thank you for pointing this out. 
As suggested , we will test the changes for BC break.
@giteshk need your suggestion here.

**Comment by mxr576** [comment]
Cross posting this here in from https://github.com/apigee/apigee-client-php/issues/258#issuecomment-1571872906

> 243 backwards-incompatible changes detected

**Comment by divya-intelli** [comment]
@mxr576 thank you for verifying.
@giteshk

**Comment by giteshk** [comment]
I think we should open a 3.x branch as per @mxr576 's suggestion. 

2.x should be deprecated with Drupal 9 EOL.

**Comment by divya-intelli** [comment]
Created 3.x branch with Symfony/Serializer 6.2 changes and released [3.0.0](https://github.com/apigee/apigee-client-php/releases/tag/3.0.0) which will be compatible with Drupal 10.
