### ISSUE TITLE
[Support] Release schedule for 3.0.2

### ISSUE THREAD

**Issue by mxr576** [apigee/apigee-client-php#319]
As part of the Drupal 10 upgrade, we identified that zthis package is only updated to a dev version (commit) because Drupal 10.1 (with core-recommended) requires symfony/options-resolver >= 6.3.0.

```
$ composer why-not apigee/apigee-client-php 3.0.1
apigee/apigee-client-php            3.0.1   requires         psr/http-message (^1.0)                            
pronovix/devportal-composer-project 3.x-dev does not require psr/http-message (but 2.0 is installed)            
apigee/apigee-client-php            3.0.1   requires         symfony/options-resolver (^5.4)                    
pronovix/devportal-composer-project 3.x-dev does not require symfony/options-resolver (but v6.3.0 is installed) 
```

Without these two commits (https://github.com/apigee/apigee-client-php/commit/ba93b3a8b912a20906dd5c6584135f0186837b75, https://github.com/apigee/apigee-client-php/commit/d8888b831ca5182917b9c78222a104b070f9818d) included in a stable release this keeps going to happen.

Is there a planned schedule for releasing 3.0.2?

**Comment by divya-intelli** [comment]
@mxr576 , we will be releasing in a day or two.

**Comment by kedarkhaire** [comment]
Hi @mxr576 
We have released the changes. 
Closing the ticket.
Thanks!

**Comment by mxr576** [comment]
https://github.com/apigee/apigee-client-php/releases/tag/3.0.2

:totoro: :+1:  thanks!
