### ISSUE TITLE
Unsubscribe from a rate plan does not work with developerId, only email

### ISSUE THREAD

**Issue by minnur** [apigee/apigee-client-php#36]
| Q            | A
| ------------ | ---
| Bug?         | yes
| New Feature? | no
| Version      | 2.0.0

#### Actual Behavior

When trying to unsubscribe from an existing rate plan I get this:
`URL id qualifier [email@email.com] does not match with the entity id [someID-0839-4057-84fc-...] or some of these entities may not exist`

#### Expected Behavior

Successfully unsubscribe form a rate plan.

#### Steps to Reproduce the behavior

The code for the subscribe/unsubscribe is in my fork. I am trying to create a patch that would temporarily solve this issue or give some ideas on how this issue could be better handled in the library.

#### Proposed Solution

Looks like `Apigee\Edge\Api\Monetization\Normalizer\EntityNormalizer::normalize` needs a special treatment for the developer ID when calling unsubscribe method. While developer entity ID is used for the subscribe to rate plan is used the unsubscribe requires actual email address as a Developer ID.

**Comment by cnovak** [comment]
We should not be using anything but email addresses as an ID for developers.  The [older client library](https://github.com/apigee/edge-php-sdk) only used `developerId` in one location and it broke after internal changes (CPS migration).  We needed to [change that code to use email instead of developerId](https://github.com/apigee/edge-php-sdk/commit/5f141f355bdef98444b89cfc740c69d7557c51c0). The `developerId` is not guaranteed to be unique.

**Comment by minnur** [comment]
Here is payload example when trying to unsubscribe:

```{"created":"2018-11-29 00:06:36","developer":{"id":"someID-000-0000-84fc-..."},"endDate":"2018-11-28 09:07:33","id":"...-0000-subscriptionID-0000-...","ratePlan":{"id":"10_cents_rate_planID"},"startDate":"2018-11-28 15:15:00","updated":"2018-11-29 00:06:36"}```

That developer[id] ='someID-000-0000-84fc-...' should be email address.

**Comment by minnur** [comment]
Here is my ugly patch so you get the idea what I am trying to achieve.
[unsubscribe-rate-plan-developer-id.patch.txt](https://github.com/apigee/apigee-client-php/files/2627181/unsubscribe-rate-plan-developer-id.patch.txt)

**Comment by mxr576** [comment]
@cnovak What do you mean we should not use the developerId as ID for a developer? Nowhere in the Monetization API or only in the unsubscribe rate plan API call?

**Comment by mxr576** [comment]
@minnur You can apply this patch on the PHP API client with [Composer Patches](https://github.com/cweagans/composer-patches) until we do not figure out a general solution for this and any related issues to this problem.

**Comment by mxr576** [comment]
Hi @minnur, the fix is available in #42 and the latest dev build for this issue. Please install the latest dev or apply the mentioned PR as a patch with composer patches.
Please let me know if it worked.
