### ISSUE TITLE
Upgrading 3.0.7 version  started using dev version of symfony/options-resolver package.

### ISSUE THREAD

**Issue by nitesh-voya** [apigee/apigee-client-php#378]
## Description
After https://github.com/apigee/apigee-client-php/pull/376 went in, a dependent package `symfony/options-resolver` version were upgraded from `^6.4.6` to `^6.4.9`.

But `symfony/options-resolver` package does not have `^6.4.9` release https://packagist.org/packages/symfony/options-resolver. SO now its upgrading to dev release `6.4.x-dev`. Which does't seems to be ideal.
## Steps to Reproduce
upgrade this project to version 3.0.7 using `composer update apigee/apigee-client-php` command.
Then notice `symfony/options-resolver (v6.4.8 => 6.4.x-dev 22ab9e9)
`
## Actual Behavior
What happened after the steps to reproduce.

## Version Info
In what version or versions of this library can you
reproduce this issue?

**Comment by kedarkhaire** [comment]
Hi @nitesh-voya 

We have looked into it and thanks for letting us know about this issue.

I agree that, there is a fault in version mis-match for the said component, and to correct it, the existing working latest version of symfony/options-resolver will be added soon in the next release.

On new/fresh install, it adds symfony/options-resolver component to v6.4.8, but on updating the client project it downgrades to v6.4.x-dev.

As we have set the minimum-stability to **_dev_**, so it does not throws any issue in installation, but it installs the v6.4.x-dev version as the required version is not available.

Thanks!
