### ISSUE TITLE
List API Products

### ISSUE THREAD

**Issue by mchljams** [apigee/apigee-client-php#46]
| Q            | A
| ------------ | ---
| Bug?         | yes
| New Feature? | no
| Version      | 2.0.0

#### Actual Behavior

When using the getEntities() method on the ApiProductController the CpsNotEnabledException is thrown. 

#### Expected Behavior

I expect to get a list of the API Products

#### Steps to Reproduce the behavior

```
    public function __construct(ApigeeClient $client)
    {
        $organization = config('config.apigee.organization');
        $this->client = new ApiProductController($organization, $client->getClient());
    }
    ...
    public function all()
    {
        return $this->client->getEntities();
    }
```

**Comment by mxr576** [comment]
Hi @mchljams!

Thanks for the detailed bug report. Please upgrade to the 2.0.1 version, it is available for a while with a fix.

https://github.com/apigee/apigee-client-php/blob/2.x/CHANGELOG.md#201---2019-02-06

**Comment by mchljams** [comment]
Thanks. That did solve the issue.
