### ISSUE TITLE
 getConsumerKey() getConsumerKey()

### ISSUE THREAD

**Issue by kpoxo6op** [apigee/apigee-client-php#50]
| Q            | A
| ------------ | ---
| Bug?         | no
| New Feature? | no
| Version      | N/A
I am very sorry that I have got a noob question. I spent a few days trying to get an app key with getConsumerKey() but have no luck so far.

#### Actual Behavior

What is the actual behavior?
N/A

#### Expected Behavior

What is the behavior you expect?
getConsumerKey() gets key from my app.

#### Steps to Reproduce the behavior

What are the steps to reproduce this bug? Please add code examples,
screenshots or links to GitHub repositories that can demonstrate the problem.
..
    // Create a new developer.
    $dc = new DeveloperController($clientFactory->getOrganization(), $clientFactory->getClient());
    $developer = new Developer(['email' => $developerEmail]);
    $developer->setUserName($username);
    $developer->setFirstName($fname);
    $developer->setLastName($lname);
    $developer->setAttributes(new AttributesProperty(['CONSUMER_TYPE' => 'PMS_VENDOR']));
    $dc->create($developer);

    // Create a new developer app. - works fine
    $dac = new DeveloperAppController($clientFactory->getOrganization(), $developerEmail, $clientFactory->getClient());
    $developerApp = new DeveloperApp(['name' => $appName]);
    $developerApp->setDisplayName($appName);
    $dac->create($developerApp);

    // get consumer key. - does not work
    $appId = $developerApp->getAppid();
    $appCredential = new AppCredential(['appId' => $appId]);
    $consumerKey = $appCredential->getConsumerKey();

#### Proposed Solution
can we get example how to use getConsumerKey please?

**Comment by mxr576** [comment]
Hi @kpoxo6op, thanks for hacking with new PHP API client :)

An example that covers your question is available here: https://github.com/apigee/apigee-client-php/blob/2.0.1/examples/create_new_app_with_credential.php.

This is how you can access to all credentials provided by an app:
https://github.com/apigee/apigee-client-php/blob/2.0.1/examples/create_new_app_with_credential.php#L48

After you have created/generated a new API key for an app, do not forget to reload the app object by using the `load()` method on a `DeveloperAppController` object instance with the app id.

**Comment by kpoxo6op** [comment]
thanks a lot, this is how I made it:
```
try {
    // Create a new developer.
    $dc = new DeveloperController($clientFactory->getOrganization(), $clientFactory->getClient());
    $developer = new Developer(['email' => $developerEmail]);
    $developer->setUserName($username);
    $developer->setFirstName($fname);
    $developer->setLastName($lname);
    $dc->create($developer);

    // Create a new developer app.
    $dac = new DeveloperAppController($clientFactory->getOrganization(), $developerEmail, $clientFactory->getClient());
    $developerApp = new DeveloperApp(['name' => $appName]);
    $developerApp->setDisplayName($appName);
    $dac->create($developerApp);

    // Add Product
    // Display  consumer key.
    $dacc = new DeveloperAppCredentialController($clientFactory->getOrganization(), $developerEmail, $developerApp->id(), $clientFactory->getClient());
    $dac = new DeveloperAppController($clientFactory->getOrganization(), $developerEmail, $clientFactory->getClient());
    $appCredentials = $developerApp->getCredentials();
    $credential = reset($appCredentials);
    if ($environment == "Production") {
        $apiProducts = ['Directory API PROD V2'];
    } elseif ($environment == "UAT") {
        $apiProducts = ['Directory API UAT'];
    } else {
        $apiProducts = ['Directory API UAT'];
    }    
    $dacc->addProducts($credential->id(), $apiProducts);
    echo $credential->id();
} catch


```

**Comment by mxr576** [comment]
Looks good :)

Just to be mentioned, you can pass all _property values_ as constructor parameters to Edge entity objects:

```php
<?php
    $developer = new Developer(['email' => $developerEmail, 'userName' => $username, 'firstName' => $fname, 'lastName' => $lname]);
    // This is exceptional because display name is stored in an attribute on Apigee Edge.
    $developerApp = new DeveloperApp(['name' => $appName]);
    $developerApp->setDisplayName($appName);
```
