### ISSUE TITLE
Docs: Update install instructions

### ISSUE THREAD

**Issue by arunz6161** [apigee/apigee-client-php#56]
After a new version released from the PHP API Client with the change in https://github.com/apigee/apigee-client-php/pull/54, the install instructions of the Apigee Edge module needs to be updated all places.

For example:https://www.drupal.org/docs/8/modules/apigee-edge/configure-the-connection-to-apigee-edge#configuring-oauth2-authentication-for-apigee-edge

**Comment by mxr576** [comment]
Hi @arunz6161, yes they have to be updated but it is not a PHP API client issue. The documentations that have to be updated are in Drupal.org and maybe on docs.apigeee.com. We already have an issue in JIRA in the Docs epic for this.
