### ISSUE TITLE
Add Google OAuth authentication

### ISSUE THREAD

**Issue by arunz6161** [apigee/apigee-client-php#63]
Use account key to create and sign a JWT (JSON Web Token) that is sent to the Google OAuth 2.0 Authorization Server, which returns an access token. The token can then be used in the authorization header (Authorization: Bearer TOKEN) in making calls to the API. When the token expires, the application repeats the process.

**Comment by arlina-espinoza** [comment]
The new authentication could probably extend the class` Apigee\Edge\HttpClient\Plugin\Authentication\Oauth`.

**Comment by arlina-espinoza** [comment]
@arunz6161 / @cnovak : 
I'm working on Hybrid authentication using JWT, and I ran into a blocker. I'm following the implementation on [Using OAuth 2.0 for Server to Server Applications](https://developers.google.com/identity/protocols/OAuth2ServiceAccount), and to request the token we must specify the"scopes" that our application needs access to. However, I don't see "_apigee_" documented in https://developers.google.com/identity/protocols/googlescopes. Do you think this is something you can see directly on IAM on my service account configuration? Or could you forward my question to someone who can point is in the right direction please.

**Comment by arunz6161** [comment]
@arlina-espinoza as discussed we can use cloud-platform scope which is listed in the discovery document : https://apigee.googleapis.com/$discovery/rest?version=v1sc

**Comment by cnovak** [comment]
For now the scope is https://www.googleapis.com/auth/cloud-platform for Apigee API

**Comment by arlina-espinoza** [comment]
Resolved by #71.
