### ISSUE TITLE
Change ClientInterface::DEFAULT_ENDPOINT for PUBLIC_CLOUD_ENDPOINT 

### ISSUE THREAD

**Issue by arlina-espinoza** [apigee/apigee-client-php#76]
Changing `ClientInterface::DEFAULT_ENDPOINT` for `ClientInterface::PUBLIC_CLOUD_ENDPOINT` should make things more clear since there isn't a default endpoint anymore.
This would involve deprecating `ClientInterface::DEFAULT_ENDPOINT` in favor of the new `ClientInterface::PUBLIC_CLOUD_ENDPOINT`.

**Comment by arunz6161** [comment]
Since this a breaking change, we will consider this during next major version.

**Comment by cnovak** [comment]
TODO: Make sure to double check the naming of "hybrid" and "public cloud", since the names `SAAS_NG` and `CLASSIC` may be better naming convention, depending on how the marketing/product naming comes out.

**Comment by cnovak** [comment]
Duplicate of #112
