### ISSUE TITLE
Fix travis tests

### ISSUE THREAD

**Issue by arlina-espinoza** [apigee/apigee-client-php#78]
**Describe the bug**
Tests are failing when running with `DEPENDENCIES=""`, but not with `DEPENDENCIES="--prefer-lowest"`, as seen in: 
https://travis-ci.org/apigee/apigee-client-php/builds/604140258

Last successful 2.x build was on [08/25/2019](https://travis-ci.org/apigee/apigee-client-php/builds/576553123), and it failed next on [08/27/2019](https://travis-ci.org/apigee/apigee-client-php/builds/577552892). That should help us debug what is the dependency that is failing and if it is affecting something in the library.

Locally, it only fails if xdebug is enabled - might also be worth testing if it's related.

**Comment by mxr576** [comment]
Do not see what could be the problem exactly based on the release notes, but it seems from the Travis logs, since this update the CS Fixer acting weird: https://github.com/FriendsOfPHP/PHP-CS-Fixer/releases/tag/v2.15.2
