### ISSUE TITLE
Actualize copyright headers

### ISSUE THREAD

**Issue by mxr576** [apigee/apigee-client-php#79]
Moved conversation from an active PR: https://github.com/apigee/apigee-client-php/pull/71#issuecomment-547275120

@cnovak please share your thoughts about it. I would not drop the license header plugin unless it is actually a legal requirement having different copyright headers on older files.

**Comment by cnovak** [comment]
The files need:

> 1. the word Copyright
> 2. the year the file was created in full numeric form (e.g., 2010); don't change this if you edit, move, or copy the file.
> 3. the author (Google LLC)
> 
> All of these must be together on a single line.

**Comment by mxr576** [comment]
> the year the file was created
> don't change this if you edit, move, or copy the file.

Ahh, so this is a tricky part... I would check how complicated would it be convincing PHPCSFixer about not changing dates in header comments. It seems there is no OOTB option for that yet, although it should be possible to write a custom PHPCSFixer fixer based on the header comment fixer that adds a copyright header with the current year to new files, and ensures the header exists on other files.

https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/4625

**Comment by arlina-espinoza** [comment]
Closing this issue in favor of this other one that follows up on adding the validation back in a new way: https://github.com/apigee/apigee-client-php/issues/81
