### ISSUE TITLE
Run automated tests with real Hybrid org connections

### ISSUE THREAD

**Issue by mxr576** [apigee/apigee-client-php#89]
Just like there is an option to run all tests with offline data set or a real (non-hybrid) Apigee connection locally or on a CI ([by setting up predefined environments variables](https://github.com/apigee/apigee-client-php#unit-tests)), provide a way to also run a test build with a real connection to a hybrid org. This could help automatically identifying broken features on hybrid-enabled orgs.

Ex.: #88 #85

**Comment by cnovak** [comment]
Closing #72 & #73 as duplicates of this ticket. We need to stand up a hybrid org for this.
